### ISSUE TITLE
Set up CI (Travis CI), Coveralls and SonarQube

### ISSUE THREAD

**Issue by diegobugmann** [TheCodingKittens/CK-BE#5]
## Development Tasks:
- [x] TheCodingKittens/CK-BE#9
- [x] TheCodingKittens/CK-BE#10
- [x] TheCodingKittens/CK-BE#11
- [x] TheCodingKittens/CK-UI#17
- [x] TheCodingKittens/CK-UI#18
- [x] TheCodingKittens/CK-UI#19
