### ISSUE TITLE
Dockerize Application

### ISSUE THREAD

**Issue by diegobugmann** [TheCodingKittens/CK-BE#8]
## Development Tasks:
- [x] TheCodingKittens/CK-UI#16
- [x] TheCodingKittens/CK-BE#13
- [x] TheCodingKittens/CK-BE#14
- [x] TheCodingKittens/CK-BE#15
